### DISCUSSION TITLE
Error while dockerizing an adonisJS + mysql application

### DISCUSSION THREAD

**Discussion by HK770** [adonisjs/core#1419] [Help]
Hi.

I am trying to dockerize an adonisJS + mysql application. When i run **docker-compose up -d** this happens:

WARNING: The DB_USER variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_ALLOW_EMPTY_PASSWORD variable is not set. Defaulting to a blank string.
Creating newslet_adonis-mysql_1 ... done
Creating tool-api               ... done

However, when I go to http://0.0.0.0:3333, I get the error **This site can’t be reached, 0.0.0.0 refused to connect.** When I do **docker ps** no containers are running. Please help

Dockerfile:
```
FROM node

ENV HOME=/app

RUN mkdir /app

WORKDIR $HOME

COPY . .

RUN npm i -g @adonisjs/cli && npm install

CMD ["docker-start.sh"]
```
.env file
```
HOST=0.0.0.0
PORT=3333
NODE_ENV=development
APP_URL=http://${HOST}:${PORT}
CACHE_VIEWS=false
APP_KEY=
DB_CONNECTION=mysql
DB_HOST= adonis-mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=
DB_ALLOW_EMPTY_PASSWORD=yes
DB_DATABASE=newsletter
DB_SOCKETPATH=
SESSION_DRIVER=cookie
HASH_DRIVER=bcrypt
APP_NAME=tool

MAIL_CONNECTION=smtp
SMTP_HOST=smtp.mailtrap.io
MAIL_USERNAME=
MAIL_PASSWORD=
```
docker-start.sh
```
echo "\n\n\nNpm install:"
npm install

echo "\n\n\nGetting key:"
adonis key:generate


echo "\n\n\nRun migration:"
adonis migration:run --seed

echo "\n\n\nStart node server:"
adonis serve --dev
```
docker-compose.yml
```
version: '3'

services:
  adonis-mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - $PWD/data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
    networks:
      - api-network
  adonis-api:
    container_name: "tool-api"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - adonis-mysql
    networks:
      - api-network

networks: 
  api-network:
```
