### DISCUSSION TITLE
[v5] Bcrypt Hash driver not working on Docker

### DISCUSSION THREAD

**Discussion by rrmesquita** [adonisjs/core#1869] [Help] [answered]
Using `bcrypt` as hash driver (with `phc-bcrypt` lib installed) is causing the HTTP server to suddenly stop.

```ts
import Hash from '@ioc:Adonis/Core/Hash'

Route.get('/', async () => {
  return { hello: await Hash.make('world') }
})
```

The simple snippet above will cause the server to throw the following:

`[ warn ]  Underlying HTTP server died with "null code"`

I'm using a docker-compose setup but I've tried with `argon` driver and it worked just fine. The hash config file is untouched.

**Comment by a-coruble** [comment]
Hi, have you modified the `config/hash.ts` to use the bcrypt config ? You can do that either by adding `HASH_DRIVER=bcrypt` to your `.env` file or either by changing the default in the config file.

If you open the `config/hash.ts`, there is a line in the config with a `default: Env.get('HASH_DRIVER', 'argon'),`, replace it by `default: Env.get('HASH_DRIVER', 'bcrypt'),`

**Reply by rrmesquita** [reply]
Hey man, the bcrypt driver is already being used, but thanks!

**Comment by thetutlage** [comment]
@rodrigoriome It is really hard to know the reason behind the issue without looking at any stack trace. Do you see any exception on the console? 

- If do, then please share the complete trace.
- If not, then run your code as `node -r @adonisjs/assembler/build/register server.ts` and then see if you see any stack trace

**Reply by rrmesquita** [reply]
Hmm, no stack trace at all. This is the closest as I got from a response (docker-compose output):

```
adonis_app       | [1605052662960] INFO    (adonis-project/1 on 0a682bc65e47): started server on 0.0.0.0:3333
adonis_database  | 2020-11-10T23:58:13.489525Z 4 [Note] Aborted connection 4 to db: 'adonis' user: 'adonis' host: '172.20.0.6' (Got an error reading communication packets)
```

Here is my environment:

```Dockerfile
# Dockerfile

FROM node:12-alpine AS basic
RUN mkdir -p /home/node/app/node_modules
WORKDIR /home/node/app
RUN apk add --no-cache git
EXPOSE $PORT

FROM basic AS builder
COPY package.json ./
COPY . .
RUN chown -R node:node /home/node
RUN npm install
USER node
RUN npm run build
CMD [ "npm", "run", "dev" ]
```

```yaml
# docker-composer.yml

version: '3.6'

services:
  app:
    container_name: adonis_app
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}

  database:
    container_name: adonis_database
    image: mysql:5.7
    restart: always
    ports:
      - ${DOCKER_PORT_DB}:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    container_name: adonis_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${DOCKER_PORT_PMA}:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    links:
      - database
    depends_on:
      - database

  meilisearch:
    container_name: adonis_meilisearch
    image: getmeili/meilisearch:v0.15.0
    ports:
      - ${DOCKER_PORT_MEILISEARCH}:7700
    volumes:
      - ml_data:/data.ms

  redis:
    container_name: adonis_redis
    image: redis:6-alpine
    ports:
      - ${DOCKER_PORT_REDIS}:6379
    volumes:
      - redis_data:/data

volumes:
  db_data:
  ml_data:
  redis_data:
```
