### DISCUSSION TITLE
How to perform a basic CI test with GitLab

### DISCUSSION THREAD

**Discussion by dajpes** [adonisjs/core#2088] [Help] [answered]
Hello Everybody, 

I have a question, how should I config the gitlab-ci.yml in order to create a basic ci test  every time I push some changes to the gitlab Repo?

I'm using   [Japa test files](https://preview.adonisjs.com/blog/running-tests-in-adonisjs-v5) along with the [october update](https://preview.adonisjs.com/blog/october-2020-release) with this gitlab-ci.yml file. Of course this file doesn't wanna work:

```
stages:
  - test

.test-shared: &test-shared
  image: node:alpine
  cache:
    key: '$CI_JOB_NAME'
    paths:
      - .node_modules/
  before_script:
    - npm install

test:
  stage: test 
  <<: *test-shared
  services:
    - name: mariadb
  variables:
    ENV_SILENT: "true"
    MYSQL_DATABASE: myDb
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_USER: root
    MYSQL_HOST: mariadb
  before_script:
    - apk update
    - apk add mysql-client
  script:
    - npm run test"
```

Using that file I have two errors, the first one is that ".node_modules/" file doesn't exist, even if I change the file to "node_modules" or "node_modules/" the error persist.

The second and more important error is the "npm run test" fail when it starts. The gitlab online console output this:
![image](https://user-images.githubusercontent.com/11248816/103308926-a9ca2a80-49e1-11eb-9799-91309784ebd8.png)

Do you have any suggestions?

**Comment by dajpes** [comment, marked as answer]
I'm gonna anwer my self, after trying to figure this out all morning, I came up with this solution:

.gitlab-ci.yml:

```yml
stages:
  - test

.test-shared: &test-shared
  image: node:alpine

test:
  stage: test
  <<: *test-shared
  services:
    - name: mariadb
  variables:
    ENV_SILENT: "true"
    MYSQL_DATABASE: myDb
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_USER: root
    MYSQL_HOST: mariadb
  before_script:
    - apk update
    - apk add mysql-client
    - npm install
  script:
    - cp .env.testing .env
    - npm run test
```

Then I created another file called .env.testing:

```env
NODE_ENV=TESTING
APP_KEY=mySecretKey
DB_CONNECTION=mysql
HOST=127.0.0.1
DB_HOST=mariadb
DB_USER=root
DB_PASSWORD= mysql
DB_NAME=myDb
SESSION_DRIVER=cookie

MYSQL_PORT=3306
MYSQL_DB_NAME=myDb
MYSQL_PASSWORD=mysql
MYSQL_USER=root
MYSQL_HOST=mariadb
```

I generated the secret App key inside the .yml file ,like this:

```yml
  script:
#    - cp .env.testing .env
      - node ace generate:key
#    - npm run test
```
Then I ran the ci again, and finally I copied the key generated  to the .env.testing file

And that's it
