### DISCUSSION TITLE
[v5] don't build docker

### DISCUSSION THREAD

**Discussion by brandonsousa** [adonisjs/core#2819] [Help]
dockerfile:
```
FROM node:alpine3.10

RUN mkdir -p /usr/app

WORKDIR /usr/app

COPY . .

EXPOSE 80

RUN npm install --quiet
```

docker-compose
```
version: "3.1"

services:
  app:
    build: .
    command: 
      - /bin/sh
      - -c
      - |
        npm run build
        cd build
        npm i --production --force
        node server.js
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
volumes:
  node_modules:

```

app_1  | 
app_1  | > amon@1.0.0 build
app_1  | > node ace build --production
app_1  | 
app_1  | [ error ]  E_INVALID_FLAG: Unknown flag "production"
app_1  | npm notice 
app_1  | npm notice New minor version of npm available! 7.7.6 -> 7.18.1
app_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.18.1>
app_1  | npm notice Run `npm install -g npm@7.18.1` to update!
app_1  | npm notice 
app_1  | /bin/sh: cd: line 2: can't cd to build: No such file or directory      
app_1  | npm WARN using --force Recommended protections disabled.
app_1  | 
app_1  | up to date, audited 340 packages in 3s
app_1  | 
app_1  | 30 packages are looking for funding
app_1  |   run `npm fund` for details
app_1  |
app_1  | found 0 vulnerabilities
app_1  | node:internal/modules/cjs/loader:927
app_1  |   throw err;
app_1  |   ^
app_1  |
app_1  | Error: Cannot find module '/usr/app/server.js'
app_1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
app_1  |     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
app_1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
app_1  |     at node:internal/main/run_main_module:17:47 {
app_1  |   code: 'MODULE_NOT_FOUND',
app_1  |   requireStack: []
app_1  | }
app_1  | 
app_1  | > amon@1.0.0 build
app_1  | > node ace build --production
app_1  |
app_1  | [ error ]  E_INVALID_FLAG: Unknown flag "production"
app_1  | /bin/sh: cd: line 2: can't cd to build: No such file or directory
app_1  | npm WARN using --force Recommended protections disabled.
app_1  | 
app_1  | up to date, audited 340 packages in 2s
app_1  |
app_1  | 30 packages are looking for funding
app_1  |   run `npm fund` for details
app_1  |
app_1  | found 0 vulnerabilities
app_1  | node:internal/modules/cjs/loader:927
app_1  |   throw err;
app_1  |   ^
app_1  |
app_1  | Error: Cannot find module '/usr/app/server.js'
app_1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
app_1  |     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
app_1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
app_1  |     at node:internal/main/run_main_module:17:47 {
app_1  |   code: 'MODULE_NOT_FOUND',
app_1  |   requireStack: []
app_1  | }
