### DISCUSSION TITLE
[v4] How can i build a local docker development env for Adonis?

### DISCUSSION THREAD

**Discussion by wemersonrv** [adonisjs/core#2907] [Help] [answered]
Hello guys

Can anyone recommend a tutorial to build a local docker development environment for Adonis?

I already created a local environment. But the the `npm install` is fixed when it was builded. And as is a development environment, I need to run `npm` comands inside container to install new packages, instal, remove, etc.

How can i do that?

My current docker files:

**doccker-compose.yaml**
```yaml
version: '3'
services:
  wwjsnode:
    image: wwjs/node:16-alpine
    environment:
      HOST: '0.0.0.0'
    ports:
      - '${PORT:-3333}:3333'
    build:
      context: .
      dockerfile: NODE.dockerfile
    volumes:
      - '.:/home/wwjs'
      - '/home/wwjs/node_modules'
    networks:
      - wwjs
    command: adonis serve --dev
    depends_on:
      - pgsql
      - redis
  pgsql:
    image: 'postgres:13'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - wwjs
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USER}']
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - wwjs
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
networks:
  wwjs:
    driver: bridge
volumes:
  pgsql:
    driver: local
  redis:
    driver: local
```

**NODE.Dockerfile**
```bash
FROM node:16-alpine

WORKDIR /home/wwjs

COPY package*.json ./

RUN npm i -g @adonisjs/cli \
    && npm install

COPY . .

ARG PORT

EXPOSE $PORT
```
