### DISCUSSION TITLE
Docker compose strange permission error issue

### DISCUSSION THREAD

**Discussion by melokki** [adonisjs/core#3562] [Help]
Hi there again
I am having this issue with docker that I cannot understand
I've created 3 micro services, all of them are adonis apps. All of thme uses the same `Dockerfile`. When I start them with `docker-coompose` only one of them does not want to work properly.

I get the following error:

```
EACCES: permission denied, unlink '/code/node_modules/.cache/adonis-require-ts
```

I don't understand why the other 2 micro services are running just fine, but this one throws this error

This is the `Dockerfile` of the micro service

```
FROM node:17-alpine

ENV ENV_SILENT=true

WORKDIR /code

COPY . .

RUN npm config set unsafe-perm true

EXPOSE 3334

ENTRYPOINT [ "npm", "run", "dev" ]
```

and this is what I have in `docker-compose.yml` for this service

```
services:
  notifications:
    build:
      context: ./../../../notifications
      dockerfile: ./Dockerfile
    ports:
      - "3334:3334"
    volumes:
      - "./../../../notifications:/code"
    networks:
      - database
      - code
```

The other 2 micro services have the same `Dockerfile` the only thing that differs is the exposed port
