### DISCUSSION TITLE
How to run Japa tests in CI

### DISCUSSION THREAD

**Discussion by evoactivity** [adonisjs/core#3758] [Cookbooks]
I have put together a bare bones example of running the adonis test suite using github actions.

This is as simple as the workflow can be, additional caching could be added to speed up the installation steps etc but I think keeping it as simple as possible allows people to more easily adjust it to fit their needs.

The action is configured to run on each push and it will
1. Run on node 16.15.1 and 18.3.0
2. Setup Postgres and Redis docker containers
3. Setup a node container to run the adonis application
4. run `node ace test`

You will need to 
1. Replace all instances of ProjectName (postgres database ENV vars)
2. Modify the node versions you want to run on
3. Add any ENV vars needed by adonis and your tests at the bottom
4. Your tests should [migrate and seed your database](https://docs.adonisjs.com/guides/testing/introduction#database-management) 

```yaml
name: ProjectName CI Tests
on: push

jobs:
  japa-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.15.1', '18.3.0']

    container:
      image: node:${{ matrix.node-version }}

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres
        env:
          POSTGRES_USER: ProjectName
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ProjectName-test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: node ace test
        env:
          DB_CONNECTION: pg
          PG_HOST: postgres
          PG_PORT: 5432
          PG_USER: ProjectName
          PG_PASSWORD: password
          PG_DB_NAME: ProjectName-test
          REDIS_CONNECTION: local
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_PASSWORD:
          APP_KEY: somefakekeythatis>16characters
          NODE_ENV: test
          ASSETS_DRIVER: fake
          SESSION_DRIVER: memory
          CACHE_VIEWS: false
          DRIVE_DISK: local
```

What would be good to see is people contributing configs for other CI tools for instance a GitLab CI config, Travis, Jenkins etc. I would love to collect a set of bare bones configs to share with the community. So if you can, please share in this thread the configurations you are using to build, test and or deploy your adonis applications it would be great to come to a community consensus on best practices.

Ultimately these configs could make their way back into Adonis's templates so all new projects can come per-configured to test in CI.

I hope this helps someone else get started with their CI workflow :)
