### DISCUSSION TITLE
How to make Encore work with Docker?

### DISCUSSION THREAD

**Discussion by SqueedWalz** [adonisjs/core#3865] [Help]
I have setup an Adonis project using Docker, all worked great until I added Encore, now the assets (js and css) are not loading. In my development environment I can see that it tries to fetch the asset files using `http://0.0.0.0:8080/assets` as host and port, when I manually go to `http://localhost:8080/assets` I can see the assets. How do I get it to work in my dev env using Docker and Encore.

**.env**
```
PORT=3333
HOST=0.0.0.0
NODE_ENV=development
...
```

docker-compose.yml
```
...
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
      - 8080:8080
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --encore-args="--host ${HOST} --port 8080"
```

If I manually go in and change the entrypoint.json file paths to use localhost and then reload the page it works, but not with the auto-generated 0.0.0.0 host.

I have tried to change HOST in my .env file to localhost without any success.

![encore](https://user-images.githubusercontent.com/47356729/184651251-fa0ce0ba-2daf-4b1b-913c-7ca1e87b7c82.jpg)

I have also noted that the changes I do in the js and css files in the resources folder are only showing if I restart the dev environment, does not "hot load". But the changes I do in the edge templates show immediately after refresh.
And if I change the entrypoint.json file in the public folder to use localhost instead of 0.0.0.0 manually all the js and css gets loaded correctly, but as soon as I restart the dev environment it changes back to 0.0.0.0 in the entrypoint.json.

![docker](https://user-images.githubusercontent.com/47356729/184811186-12a8962f-bab8-4b36-8de4-8179aad56612.jpg)

This is how the startup of the application looks in Docker.

Anyone has any ideas on what is missing?
