### DISCUSSION TITLE
Help needed with error "Underlying HTTP server died with "null code"" using phc-argon2

### DISCUSSION THREAD

**Discussion by danieljcksn** [adonisjs/core#4062] [Help]
Hello,

I am using argon2 in my AdonisJS application for hashing passwords of users. I have followed the instructions from the official documentation but I am encountering an error when I make a request to a route that uses the hashing (e.g. the users route): 'Underlying HTTP server died with "null code"'.

Here is my dockerfile:
```
ARG NODE_IMAGE=node:16.13.1-alpine

FROM $NODE_IMAGE AS base
RUN apk add --no-cache python3
RUN apk --no-cache add dumb-init
RUN mkdir -p /home/node/app && chown node:node /home/node/app
WORKDIR /home/node/app
USER node
RUN mkdir tmp

FROM base AS dependencies
COPY --chown=node:node ./package*.json ./
RUN npm ci
COPY --chown=node:node . .

FROM dependencies AS build
RUN node ace build --production

FROM base AS production
ENV NODE_ENV=production
ENV PORT=$PORT
ENV HOST=0.0.0.0
COPY --chown=node:node ./package*.json ./
RUN npm ci --production
COPY --chown=node:node --from=build /home/node/app/build .
EXPOSE $PORT
CMD [ "dumb-init", "node", "server.js" ]
```

And here is my docker compose:
```
version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  postgres_volume:
```

Could someone please help me to resolve this error? Any help would be greatly appreciated.

Thank you.
