### DISCUSSION TITLE
Docker Adonis[V6] API, Mysql, PHPMyadmin, Redis

### DISCUSSION THREAD

**Discussion by CRodolfosa** [adonisjs/core#4549] [Help] [answered]
Hello, I'm new to AdonisJS, I created an api containing mysql, phpmyadmin and redis.
When I run normally in my WSL I receive the return "hello Works!" in the api.
When I run it through Docker I can't run localhost:3333

I'll post my docker configuration files, anyone who can help would be grateful!

Dockfile
```
ARG NODE_IMAGE=node:20.11.1-alpine

FROM $NODE_IMAGE AS base
RUN apk --no-cache add dumb-init
RUN mkdir -p /home/node/app && chown node:node /home/node/app
WORKDIR /home/node/app
USER node
RUN mkdir tmp

FROM base AS dependencies
COPY --chown=node:node ./package*.json ./
RUN npm ci
COPY --chown=node:node . .

FROM dependencies AS build
RUN node ace build --production

FROM base AS production
ENV NODE_ENV=production
ENV PORT=$PORT
ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true
COPY --chown=node:node ./package*.json ./
RUN npm ci --production
COPY --chown=node:node --from=build /home/node/app/build .
EXPOSE $PORT
CMD [ "dumb-init", "node", "server.js" ]
```
docker-compose.yml
```
version: '3.8'

services:
  mysql:
    container_name: mysql
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-rodolfo
      MYSQL_ROOT_USER: root
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: adonis
      PMA_PASSWORD: adonis
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - $PWD/dockerConfig/mysql-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    mem_limit: 512m
    networks:
      - mysqlnetwork
  
  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mysql-phpmyadmin
    ports:
      - "8001:80"
    mem_limit: 512m
    networks:
      - mysqlnetwork
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: adonis
      PMA_PASSWORD: adonis

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
     - redis_volume:/data
    ports:
      - 6379:6379
    mem_limit: 96m
    networks:
      - mysqlnetwork

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - mysql
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch 
volumes:
  mysql_volume:
  redis_volume:
networks:
  mysqlnetwork:
    driver: bridge

```

.env
```
TZ=UTC
PORT=3333
HOST=localhost
LOG_LEVEL=info
APP_KEY=ug-G4vkvOzPQidnzl6t0cOvIhxNGSMaf
NODE_ENV=development
DB_HOST=mysql
DB_PORT=3306
DB_USER=adonis
DB_PASSWORD=adonis
DB_DATABASE=api-rodolfo
REDIS_HOST=0.0.0.0
REDIS_PORT=6379
REDIS_PASSWORD=
```
config/cors.ts
```
import { defineConfig } from '@adonisjs/cors'

/**
 * Configuration options to tweak the CORS policy. The following
 * options are documented on the official documentation website.
 *
 * https://docs.adonisjs.com/guides/security/cors
 */
const corsConfig = defineConfig({
  enabled: true,
  origin: '*',
  methods: ['GET', 'HEAD', 'POST', 'PUT', 'DELETE'],
  headers: "Access-Control-Allow-Origin' '*'",
  exposeHeaders: [],
  credentials: true,
  maxAge: 90,
})


export default corsConfig
```
dockerConfig
```
CREATE USER 'adonis' IDENTIFIED BY 'adonis';
CREATE DATABASE adonis_app;
GRANT ALL PRIVILEGES ON adonis_app.* TO 'adonis';
```
![image](https://github.com/adonisjs/core/assets/115118921/e36354a6-2478-4a4b-ad95-2b583a81bdd0)
![image](https://github.com/adonisjs/core/assets/115118921/2c5d36ce-004b-4506-99d1-d7064fab91d7)
![image](https://github.com/adonisjs/core/assets/115118921/38191277-9891-47b2-97ae-40cb10adaace)
