### DISCUSSION TITLE
My test runner is broken

### DISCUSSION THREAD

**Discussion by jorisvilardell** [adonisjs/core#4739] [Help] [answered]
Hello I learn how to do CI and I want to make a test runner with github workflow. This my runner:
```yaml
name: Run Adonis Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2q-back/

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: e2q
          POSTGRES_PASSWORD: e2q-test-runner
          POSTGRES_DB: E2Q-Test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # Install VLC (the missing dependency)
      - name: Install VLC
        run: sudo apt-get update && sudo apt-get install -y vlc

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Run DB migration & seed
        run: pnpm run rundb
        env:
          TZ: UTC
          PORT: 3333
          HOST: localhost
          LOG_LEVEL: info
          APP_KEY: TestingEnvironnement-E2QRunnerTe
          NODE_ENV: test

          DB_HOST: localhost
          DB_CONNECTION: pg
          DB_PORT: 5432
          DB_USER: e2q
          DB_PASSWORD: e2q-test-runner
          DB_DATABASE: E2Q-Test

          ADMIN_IDENTIFIANT: admin-test
          ADMIN_PASSWORD: admin-test

      - name: Run tests
        run: pnpm run test
        env:
          TZ: UTC
          PORT: 3333
          HOST: localhost
          LOG_LEVEL: info
          APP_KEY: TestingEnvironnement-E2QRunnerTe
          NODE_ENV: test

          DB_HOST: localhost
          DB_CONNECTION: pg
          DB_PORT: 5432
          DB_USER: e2q
          DB_PASSWORD: e2q-test-runner
          DB_DATABASE: E2Q-Test

          ADMIN_IDENTIFIANT: admin-test
          ADMIN_PASSWORD: admin-test
```

This the error I got during `npm ci` :

```console
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net/
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm error code 1
npm error path /home/runner/work/E2Q/E2Q/e2q-back/node_modules/vlc-static
npm error command failed
npm error command sh -c node install
npm error /home/runner/work/E2Q/E2Q/e2q-back/node_modules/which/which.js:10
npm error   Object.assign(new Error(`not found: ${cmd}`), { code: 'ENOENT' })
npm error                 ^
npm error
npm error Error: not found: vlc
npm error     at getNotFoundError (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/which/which.js:10:17)
npm error     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/which/which.js:57:18
npm error     at new Promise (<anonymous>)
npm error     at step (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/which/which.js:54:21)
npm error     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/which/which.js:71:22
npm error     at new Promise (<anonymous>)
npm error     at subStep (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/which/which.js:69:33)
npm error     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/which/which.js:80:22
npm error     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/isexe/index.js:42:5
npm error     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/isexe/mode.js:8:5 {
npm error   code: 'ENOENT'
npm error }
npm error
npm error Node.js v18.20.4
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-09-30T01_16_26_685Z-debug-0.log
```

I don't understand what is wrong. I tried to delete my package-lock but it's not fixed.

**Comment by NathaelB** [comment]
Maybe install vlc in your container/vm ?

```diff
+ # Install VLC (the missing dependency)
+ - name: Install VLC
+   run: sudo apt-get update && sudo apt-get install -y vlc
```

**Reply by jorisvilardell** [reply]
```
[12:50:31.926] ERROR (4444): Knex: run
$ npm install pg --save
Cannot find module 'pg'
Require stack:
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/dialects/postgres/index.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/dialects/index.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/knex-builder/Knex.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/index.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/knex.js
Error: Cannot find module 'pg'
Require stack:
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/dialects/postgres/index.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/dialects/index.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/knex-builder/Knex.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/index.js
- /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/knex.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Client_PG._driver (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/dialects/postgres/index.js:63:12)
    at Client_PG.initializeDriver (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/client.js:198:26)
    at new Client (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/client.js:83:12)
    at new Client_PG (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/dialects/postgres/index.js:21:5)
    at Function.knex (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/knex@3.1.0_mysql2@3.11.3/node_modules/knex/lib/knex-builder/Knex.js:16:28)
    at Connection.setupWriteConnection (file:///home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/@adonisjs+lucid@20.6.0_@adonisjs+assembler@7.8.2_typescript@5.6.2__@adonisjs+core@6.14.0_@ado_qxvypb6ihdoqafq53nf4s32pru/node_modules/@adonisjs/lucid/build/src/connection/index.js:197:28)
```

thx u vlc work but know the problem is with adonis db connection.

**Comment by jorisvilardell** [comment, marked as answer]
Thank you @NathaelB !
```yaml
# Install VLC (the missing dependency)
- name: Install VLC
  run: sudo apt-get update && sudo apt-get install -y vlc
```

[https://github.com/orgs/adonisjs/discussions/4741](https://github.com/orgs/adonisjs/discussions/4741)
