### DISCUSSION TITLE
Hot Reload not working with Docker and AdonisJS

### DISCUSSION THREAD

**Discussion by Crim-oo** [adonisjs/core#4835] [Help]
Hi,

I’m using AdonisJS in a Docker-based development environment. To detect file changes and enable a fast feedback loop during development, I started using the --poll flag (node ace serve --poll). I’ve noticed that changes do not reflect in the application without manually restarting the server. 

**Dockerfile**
```
FROM node:20.12.2-alpine3.18

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install
```
**docker-compose.yml**
```
services:
  app:
    build:
      context: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      APP_KEY: e3VJJ4N4PJ2EAl8_4u_pjPLyAuFkUpLb
      PORT: 3333
      HOST: 0.0.0.0
    command: ['pnpm', 'dev']
```
**Scripts in package.json**
```
"scripts": {
  "start": "node bin/server.js",
  "build": "node ace build",
  "dev": "node ace serve --poll",
  "test": "node ace test",
  "lint": "eslint .",
  "format": "prettier --write .",
  "typecheck": "tsc --noEmit"
}
```
Is --poll sufficient to enable hot reloading for all files or are additional configurations required?
