### DISCUSSION TITLE
reflect-metadata is not found even though it is already installed in Docker images

### DISCUSSION THREAD

**Discussion by PinKevin** [adonisjs/core#4856] [Help]
Hello, I have a problem where my container won't start because reflect-metadata is not found. I already check it via `docker build` log and the images that I have the reflect-metadata dependency. For make this image, I directly make an image from the build directory with Dockerfile and docker-compose as follows:
```dockerfile
FROM node:lts-alpine AS base

USER root
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod

COPY . .

CMD ["node", "bin/server.js"]

```

```yml
version: '3.9'

services:
  asesmen-paud:
    image: asesmen-paud
    container_name: asesmen-paud
    restart: unless-stopped
    build:
      context: .
      target: build
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: node ace serve --watch
    depends_on:
      - asesmen-paud-postgresql

  asesmen-paud-postgresql:
    image: postgres:17
    container_name: asesmen-paud-postgresql
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
      - 5432:5432
    expose:
      - ${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  db:

```

![image](https://github.com/user-attachments/assets/bf6a2d65-f065-4731-8d18-1711d0be0de0)
![image](https://github.com/user-attachments/assets/13d57d41-be58-41cf-b72b-7fd64f806a77)

So, what's that makes it not found?
