### DISCUSSION TITLE
Breakpoints doesn't work in attach mode for docker-compose

### DISCUSSION THREAD

**Discussion by ybebesh-ventionteams** [adonisjs/core#4870] [Help] [answered]
Hey team,

Could you please support me?
I'm working on the issue regarding docker-compose + debug + vscode usage.

I have read https://github.com/orgs/adonisjs/discussions/3896, https://v5-docs.adonisjs.com/cookbooks/dockerizing-adonis

But it doesn't work for me, unfortunately. I attached my vscode for debugging, but I can't define breakpoints in ts files.

Could you please take a look at my configuration:

**docker-compose.yaml**
```
backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../backend:/home/node/app
      - /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0:9229"
    ports:
      - 3333:3333
      - 9229:9229
    env_file: "../ribeye-api/.env"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    networks:
      - app-network
```

**Dockerfile**
```
ARG NODE_IMAGE=node:20.11-alpine

# Stage 1: Base setup
FROM $NODE_IMAGE AS base

RUN apk --no-cache add dumb-init curl ffmpeg

WORKDIR /home/node/app

RUN npm install -g pnpm@9

# Stage 2: Build step
FROM base AS build

COPY ./package.json ./pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile && pnpm prune

COPY . .

RUN node --max-old-space-size=4096 ace build --production

RUN cp .env.example .env && node ace generate:docs && cp swagger.yml build

# Stage 3: Development image
FROM build AS development

ENV PORT=$PORT
ENV HOST=0.0.0.0
ENV NODE_ENV=development

EXPOSE $PORT

WORKDIR /home/node/app

COPY --from=build /home/node/app/build ./build
COPY --from=build /home/node/app/swagger.yml ./build/swagger.yml
COPY --from=build /home/node/app/node_modules ./node_modules
```

**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Debug Backend Service",
        "port": 9229,
        "restart": true,
        "localRoot": "${workspaceFolder}",
        "remoteRoot": "/home/node/app/"
      },
      {
        "type": "node",
        "request": "launch",
        "name": "Debug Backend Service local",
        "runtimeExecutable": "node",
        "runtimeArgs": ["ace", "serve", "--watch"],
        "internalConsoleOptions": "openOnSessionStart"
      }
    ]
  }
```

I can connect for debugging:
<img width="346" alt="image" src="https://github.com/user-attachments/assets/d206d214-b700-4fcd-ae3f-1c5ff5cb9be7" />

When I change something, for instance in `config/snowflake.ts`, I see changes in docker-compose
![image](https://github.com/user-attachments/assets/262fd8ce-a0e4-424c-abed-bf43d1d45b7c)

but breakpoints don't work :(
<img width="407" alt="image" src="https://github.com/user-attachments/assets/f7ccd1b6-4322-47a2-8df1-634f7b44bb20" />

in debug console:
<img width="443" alt="image" src="https://github.com/user-attachments/assets/b3d60e5a-512a-41eb-8709-7df20d1444af" />

P.s. Local debug works fine
